apiVersion: v1
kind: Pod
metadata:
  name: cassandra-client
spec:
  containers:
  - name: cassandra-client
    image: bitnami/cassandra:latest
    command: [ "sleep" ]
    args: [ "3600" ]
  restartPolicy: Never
